name: kraken_api
description: Dart Library for the Kraken API (https://www.kraken.com/features/api).
version: 1.0.2
author: Dimitrios Begnis <dimitribegnis@gmail.com>
homepage: https://github.com/Dimibe
repository: https://github.com/Dimibe/kraken_api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.1.5
  http: ^0.12.2

dev_dependencies:
  test: ^1.15.4

