name: kraken_api
description: Dart Library for the Kraken API (https://www.kraken.com/features/api).
version: 2.0.0-nullsafety.1
homepage: https://begnis.dev
repository: https://github.com/Dimibe/kraken_api

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^0.13.1

dev_dependencies:
  test: ^1.16.8

