name: kraken_api
description: Dart Library for the kraken api (https://api.kraken.com/0).
version: 0.0.1
author: Dimitrios Begnis <dimitribegnis@gmail.com>
homepage: https://github.com/Dimibe
repository: https://github.com/Dimibe/grouped_list

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.1.2
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.3.0

